---
pretix__packages:
  - git
  - build-essential
  - python3-dev
  - python3-venv
  - python3
  - python3-pip
  - libxml2-dev
  - libxslt1-dev
  - libffi-dev
  - zlib1g-dev
  - libssl-dev
  - gettext
  - libpq-dev
  - libjpeg-dev
  - libopenjp2-7-dev
packages__playbook_version_number: 3
packages__playbook_version_path: 'l3d.pretix.pretix.version'
