---
pretix__user: 'pretix'
pretix__group: "{{ pretix__user }}"
pretix__home: '/var/lib/pretix'
pretix__data: '/var/pretix'

# pretix condifuration
pretix__name: 'My Pretix'
pretix__address: "https://{{ inventory_hostname }}"
pretix__currency: 'EUR'
pretix__datadir: "{{ pretix__data }}/data"
pretix__db_backend: 'postgresql'
pretix__db_name: 'pretix'
pretix__db_user: 'pretix'
pretix__db_password: ''
pretix__db_host: 'localhost'

pretix__web_workers: 5
pretix__web_loglevel: 'info'
pretix__web_bind: '127.0.0.1:8345'
pretix__web_oncalendar: '*-*-* *:00:00'
pretix__web_timer_delay: '1800'

# Optional perform simple Versionscheck
submodules_versioncheck: false
