---
- name: Run simple versionscheck (optional)
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: packages__submodules_versioncheck | bool

- name: Create user for pretix
  ansible.builtin.include_tasks:
    file: 'user.yml'

- name: Install required packages
  ansible.builtin.include_tasks:
    file: 'packages.yml'
