---
- name: Run simple versionscheck (optional)
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Create user for pretix
  ansible.builtin.include_tasks:
    file: 'user.yml'

- name: Install required packages
  ansible.builtin.include_tasks:
    file: 'packages.yml'

- name: Create pretix Configuration
  ansible.builtin.include_tasks:
    file: 'configure.yml'

- name: Install pretix
  ansible.builtin.include_tasks:
    file: 'install.yml'

- name: Create systemd service
  ansible.builtin.include_tasks:
    file: 'systemd.yml'
