---
- name: Create pretix-web service unit
  become: true
  ansible.builtin.template:
    src: 'templates/pretix-web.service.j2'
    dest: '/etc/systemd/system/pretix-web.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'systemctl restart pretix-web.service'

- name: Create pretix-worker service unit
  become: true
  ansible.builtin.template:
    src: 'templates/pretix-worker.service.j2'
    dest: '/etc/systemd/system/pretix-worker.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'systemctl restart pretix-worker.service'

- name: Create pretix-cron service unit
  become: true
  ansible.builtin.template:
    src: 'templates/pretix-cron.service.j2'
    dest: '/etc/systemd/system/pretix-cron.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'systemctl restart pretix-cron.service'

- name: Create pretix-cron service timer
  become: true
  ansible.builtin.template:
    src: 'templates/pretix-cron.timer.j2'
    dest: '/etc/systemd/system/pretix-cron.timer'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'systemctl start pretix-cron.timer'

- name: Make sure services are started
  become: true
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: 'restarted'
    daemon_reload: true
    enabled: true
  with_items:
    - 'pretix-web'
    - 'pretix-worker'
    - 'pretix-cron'
