---
- name: Run simple versionscheck (optional)
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Make sure postgres is installed
  ansible.builtin.include_tasks:
    file: 'packages.yml'
  when:
    - ansible_pkg_mgr == "apt"

- name: Only apt is supported
  ansible.builtin.fail:
    msg: "Only debian based systems using apt are supported"
  when:
    - not ansible_pkg_mgr == "apt"

- name: Create pretix Configuration
  ansible.builtin.include_tasks:
    file: 'create_database.yml'
